# Generated by Django 5.1.6 on 2025-02-20 23:26

import image.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(upload_to='files/', validators=[image.models.validate_file_extension])),
                ('model', models.CharField(choices=[('rn50', 'ResNet50'), ('v16', 'Vgg16')], max_length=60, verbose_name='Модель для классификации картинки')),
            ],
        ),
    ]
